apiVersion: v1
kind: Secret
metadata:
  name: as-search-in-shvr-secrets
  namespace: eis-shvr
stringData:
  application.secret.properties: |
    spring.datasource.username=<DB_USERNAME>
    spring.datasource.password=<DB_PASSWORD>

    tfs.accessKey=<TFS_ACCESS_KEY>
    tfs.secretKey=<TFS_SECRET_KEY>

    fs.accessKey=<FS_ACCESS_KEY>
    fs.secretKey=<FS_SECRET_KEY>
