apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-ui-data
  namespace: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
