apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-auth
  namespace: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/component: admin
type: Opaque
stringData:
  # Смените пароль после первого apply
  SPRING_SECURITY_USER_NAME: admin
  SPRING_SECURITY_USER_PASSWORD: "ChangeMe-kafka-ui"
