apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-readonly
  namespace: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/component: readonly
data:
  # LOGIN_FORM в Provectus UI поддерживает только 1 пользователя на инстанс,
  # поэтому readonly — отдельный Deployment с KAFKA_CLUSTERS_0_READONLY=true
  DYNAMIC_CONFIG_ENABLED: "true"
  KAFKA_CLUSTERS_0_NAME: prod
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 10.251.86.237:9092,10.251.86.238:9092,10.251.86.239:9092
  KAFKA_CLUSTERS_0_READONLY: "true"
  AUTH_TYPE: LOGIN_FORM
