apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-auth-readonly
  namespace: kafka-ui
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/component: readonly
type: Opaque
stringData:
  # Смените пароль после первого apply
  SPRING_SECURITY_USER_NAME: readonly
  SPRING_SECURITY_USER_PASSWORD: "ChangeMe-readonly"
